### ISSUE TITLE
[css] 진행중인 드로우 페이지 레이아웃 설계

### ISSUE THREAD

**Issue by minsoftk** [JJongBin/DrawToMe#12]
- [x] : 푸터 레이아웃 설계
- [x] : 상품 검색 레이아웃 설계
- [x] : 진행중인 드로우 상품 전시 레이아웃 설계
- [ ] : 푸터에 사용될 icon들 sprite 이미지로 제작

**Comment by mei-zy** [comment]
푸터 해결 완 !

**Comment by mei-zy** [comment]
스프라이트 안씀 탕탕 !
