### ISSUE TITLE
[crossbrowsing] IE 네비게이션 스타일 안먹힘

### ISSUE THREAD

**Issue by mei-zy** [JJongBin/DrawToMe#18]
[crossbrowsing] IE 네비게이션 스타일 안먹힘

**Comment by minsoftk** [comment]
# IE
1. draw 페이지 grid repeat 속성 IE에서 지원 안하는 현상
2. 데일리 룩 슬라이드 짤림 현상. 
3. 동영상 object-fit 안먹히는 현상

**Comment by minsoftk** [comment]
- index.js와 draw.js에 ES6 문법이 사용됐는데, [참고 사이트](http://kangax.github.io/compat-table/es6/)를 확인해보니 화살표 함수를 IE11에서 지원을 하지 않는다.
- grid의 일부 속성 중 gap, auto-fill 등등 지원되지 않는 속성들이 많았다.  [can i use](https://caniuse.com/?search=grid%20repeat)

## 1번 해결
- grid에 지원되지 않는 속성들이 많아서 요소들을 어떻게 배치해야할지 고민했지만, 생각보다 까다로워 일단은 각각의 요소들이 제자리에 위치하도록 일일이 layout을 지정해줬다. 그러다보니 class 이름도 element들마다 모두 부여해야 했고, 코드가 너무 길어져서 성능도 좋지 않았다. 다른 방법도 생각해봐야 한다.
