### ISSUE TITLE
[css] main page 애니메이션 추가

### ISSUE THREAD

**Issue by JJongBin** [JJongBin/DrawToMe#53]
- [ ] 첫 화면 뷰포트 기준 스크롤 구현
- [x] header hover시 자연스러운 굵기, 밑줄
- [x] 더보기 밑줄 
- [x] daily look 균등하게 나오도록 너비 정하기

**Comment by mei-zy** [comment]
오타났어용 main 페이지

**Comment by JJongBin** [comment]
굿굿~

**Comment by mei-zy** [comment]
쫑빈 첫 뷰포트 스크롤 못한대요 클로즈 내림
