### ISSUE TITLE
[성능개선] lighthouse (개선 될 때까지 추가 예정)

### ISSUE THREAD

**Issue by JJongBin** [JJongBin/DrawToMe#88]

**Comment by JJongBin** [comment]
1. SEO 개선 ->  meta name="description" content="모시기저시기"  추가해서 성능 개선하기
2. 이미지 -> webp로 변환하던가 jpg 이미지 용량 개선

**Comment by JJongBin** [comment]
[ 진행중인 드로우 페이지]

- [x] : img alt 태그 누락
- [x] : 버튼 accessible name 누락
 => button aria-label 속성 추가로 해결 완

- [x] : Background and foreground colors do not have a sufficient contrast ratio.
👎  전경색 .. 대비율 머시기 저시기 => 조금 더 탁한 색으로 변경 완료 후 해결 완!

**Comment by mei-zy** [comment]
**상세페이지** 
- [x] :  Background and foreground colors do not have a sufficient contrast ratio.
- [x] : ARIA IDs are not unique 
- [x] : 이미지 alt 태그 누락 👎🏻 
- [x] : 라벨이랑 매치 안댐 
- [x] : meta 디스크립션
